### ISSUE TITLE
Test does not work in fabvenv-0.2.0 on PyPI

### ISSUE THREAD

**Issue by skoval00** [todddeluca/fabvenv#2]
How to reproduce.
1. Install the latest fabvenv from PyPI.
pip install fabvenv
2. Clone fabvenv from github
git clone git@github.com:todddeluca/fabvenv.git
3. Run test
cd fabvenv/tests
fab test_fabvenv

Test fails in venv.create, because fabvenv.Venv.create on PyPI does not accept any arguments.
TypeError: create() takes exactly 1 argument (2 given)

**Comment by todddeluca** [comment]
Thanks for noticing the tests were broken and including instructions for reproducing the bug.  Top notch!

I think the tests should be fixed now and I've updated the testing instructions in the README to reflect the fact that you should use an "editable" install of fabvenv that is in the same environment as fabric.

I had an old version of fabvenv installed next to fabric so that when I ran the tests, I was testing the old version, not the current code.  Oops! 

The new version is tagged 0.2.1.
